name: Django CI

on: [ push ]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}
      GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      GITHUB_SECRET: ${{ secrets.GH_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      SOCIAL_AUTH_PASSWORD: ${{ secrets.SOCIAL_AUTH_PASSWORD }}
      GOOGLE_CLIENT_PASSWORD: ${{ secrets.GOOGLE_CLIENT_PASSWORD }}
      DJANGO_SETTINGS_MODULE: GAEN.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install requirements
        working-directory: GAEN
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
